name: Automation for release on slab v2

on:
  release:
    types: [published]

jobs:
  print-username:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.release_info.outsputs.info_result }}

    steps:
      - name: Print to STDOUT
        run: echo The test worked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  latest-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Find Latest Release
        uses: actions/github-script@v3
        id: release_info
        with:
          script: |
            const query = `
            query($owner:String!, $name:String!) {
              repository(name: $name, owner: $owner) {
                latestRelease {
                  name
                  author{
                    name
                  }
                  createdAt
                  publishedAt
                  description
                }
              }
            }
            `
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              name: context.repo.repo,
            })
            console.log(result)
      - run: echo "::set-output name=info_result::$result"
  
  slab_post:
    needs: latest-release
    runs-on: ubuntu-latest
    
    steps:
      - name: Post to slab
        run: echo "${{needs.latest_release.release_info.outputs.output1}}"
