name: Automation for release on slab v2

on:
  release:
    types: [published]

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print to STDOUT
        run: echo The test worked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  latest_release:
    outputs:
      info: ${{ steps.release_info.result }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Find Latest Release
        uses: actions/github-script@v3
        
        with:
          script: |
            const query = `
            query($owner:String!, $name:String!) {
              repository(name: $name, owner: $owner) {
                latestRelease {
                  name
                  author{
                    name
                  }
                  createdAt
                  publishedAt
                  description
                }
              }
            }
            `
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              name: context.repo.repo,
            })
            console.log(result)
            return result
          result-encoding: string
          id: release_info
          run: echo "::set-output name=result::$result"

  
  slab_post:
    needs: latest_release
    runs-on: ubuntu-latest
    
    steps:
      - name: Post to slab
        run: echo "${{needs.latest_release.outputs.info}}"
