name: 'try without dockerfile'
on:
  release:
    types: [published]

jobs:
  test_with_parameters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'Go-Go-Power-Rangers/test2-action'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: Go-Go-Power-Rangers/test2-action@main
        with:
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.repository_owner }}
          accessToken_slab: "${{ secrets.SLAB_TOKEN }}"
          accessToken_github: "bearer ${{ secrets.GITHUB_TOKEN }}"
