name: release on slab automation

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            const query = '
            query {
              repository($owner:String!, $name:String!) {
                latestRelease {
                  name 
                  author {
                    name
                    }
                  createdAt
                  publishedAt
                  description
                }
              }
            }
            '
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              name: context.repo.name,
            })
            console.log(result)
