name: Automation for release on slab

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print to STDOUT
        run: echo The test worked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  latest-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Find Latest Release
        id: release
        uses: actions/github-script@v3
        with:
          script: |
            const query = `
            query($owner:String!, $name:String!) {
              repository(name: $name, owner: $owner) {
                latestRelease {
                  name
                  author{
                    name
                  }
                  createdAt
                  publishedAt
                  description
                }
              }
            }
            `
            const result = await github.graphql(query, {
              owner: context.repo.owner,
              name: context.repo.repo,
            })
            const name = result.repository.latestRelease.name
            console.log(result)
            return result
          result-encoding: string
      - name: Read result
        run: echo "${{steps.release.outputs.result}}"
            
