name: Automation for release on slab

on:
  release:
    types: [published]

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print to STDOUT
        run: echo The test worked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
